ALTER TABLE users
  ADD COLUMN IF NOT EXISTS phone VARCHAR(50) NULL AFTER role,
  ADD COLUMN IF NOT EXISTS location VARCHAR(120) NULL AFTER phone,
  ADD COLUMN IF NOT EXISTS bio TEXT NULL AFTER location,
  ADD COLUMN IF NOT EXISTS photo_url VARCHAR(500) NULL AFTER bio;
